[2024-05-02T10:14:40.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T10:14:40.256+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3-data-transfer.transfer-customer manual__2024-05-02T10:14:36.245177+00:00 [queued]>
[2024-05-02T10:14:40.262+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3-data-transfer.transfer-customer manual__2024-05-02T10:14:36.245177+00:00 [queued]>
[2024-05-02T10:14:40.262+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T10:14:40.275+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transfer-customer> on 2024-05-02 10:14:36.245177+00:00
[2024-05-02T10:14:40.284+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T10:14:40.286+0000] {standard_task_runner.py:63} INFO - Started process 2157 to run task
[2024-05-02T10:14:40.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3-data-transfer', 'transfer-customer', 'manual__2024-05-02T10:14:36.245177+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/new-dag.py', '--cfg-path', '/tmp/tmpzl49bz01']
[2024-05-02T10:14:40.288+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask transfer-customer
[2024-05-02T10:14:40.331+0000] {task_command.py:426} INFO - Running <TaskInstance: s3-data-transfer.transfer-customer manual__2024-05-02T10:14:36.245177+00:00 [running]> on host 0a71bd2d4f31
[2024-05-02T10:14:40.404+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3-data-transfer' AIRFLOW_CTX_TASK_ID='transfer-customer' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T10:14:36.245177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T10:14:36.245177+00:00'
[2024-05-02T10:14:40.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T10:14:41.207+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-02T10:14:41.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T10:14:41.216+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=s3-data-transfer, task_id=transfer-customer, execution_date=20240502T101436, start_date=20240502T101440, end_date=20240502T101441
[2024-05-02T10:14:41.261+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-02T10:14:41.273+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T10:14:41.275+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
