[2024-05-02T07:54:02.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T07:54:02.691+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3-data-transfer-dag.transfer-customer manual__2024-05-02T07:53:57.048479+00:00 [queued]>
[2024-05-02T07:54:02.700+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3-data-transfer-dag.transfer-customer manual__2024-05-02T07:53:57.048479+00:00 [queued]>
[2024-05-02T07:54:02.700+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T07:54:02.712+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transfer-customer> on 2024-05-02 07:53:57.048479+00:00
[2024-05-02T07:54:02.721+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T07:54:02.723+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2024-05-02T07:54:02.723+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3-data-transfer-dag', 'transfer-customer', 'manual__2024-05-02T07:53:57.048479+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/new-dag.py', '--cfg-path', '/tmp/tmp5xpngzvp']
[2024-05-02T07:54:02.724+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask transfer-customer
[2024-05-02T07:54:02.767+0000] {task_command.py:426} INFO - Running <TaskInstance: s3-data-transfer-dag.transfer-customer manual__2024-05-02T07:53:57.048479+00:00 [running]> on host 0a71bd2d4f31
[2024-05-02T07:54:02.843+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3-data-transfer-dag' AIRFLOW_CTX_TASK_ID='transfer-customer' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T07:53:57.048479+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T07:53:57.048479+00:00'
[2024-05-02T07:54:02.844+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T07:54:03.517+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-02T07:54:03.518+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T07:54:03.526+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=s3-data-transfer-dag, task_id=transfer-customer, execution_date=20240502T075357, start_date=20240502T075402, end_date=20240502T075403
[2024-05-02T07:54:03.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-02T07:54:03.590+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T07:54:03.592+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
